[theme]
base="light"
primaryColor="#2563EB"             
backgroundColor="#F3F4F6"          
secondaryBackgroundColor="#FFFFFF"  
textColor="#111827"                 
font="sans serif"

[server]
headless = true
enableCORS = false
