[theme]
base="light"
primaryColor="#2563EB"              # azul bonito (tipo Tailwind blue-600)
backgroundColor="#F3F4F6"           # cinza bem claro fora do formulário
secondaryBackgroundColor="#FFFFFF"  # branco dentro do formulário
textColor="#111827"                 # quase preto
font="sans serif"

[server]
headless = true
enableCORS = false
